image: alpine/latest
packages:
    - hugo
oauth: pages.sr.ht/PAGES:RW
environment:
    site: site
tasks:
    - package: |
        cd $site
        hugo
        tar -C public -cvz . > ../site.tar.gz
    - upload: |
        acurl -f https://pages.sr.ht/publish/hedy.srht.site -Fcontent=@site.tar.gz
