baseURL = "https://tilde.cafe/~hedy"
languageCode = "en-us"
title = "Hedy's Site"
uglyurls = true

[params]
src = "https://sr.ht/~hedy/site"

[permalinks]
posts = "/posts/:slug"

[markup.goldmark.renderer]
# Allows HTML in Markdown
unsafe = true

[mediaTypes]
[mediaTypes."text/gemini"]
suffixes = ["gmi"]

[outputFormats]
[outputFormats.Gemini]
name = "GEMTEXT"
isPlainText = true
isHTML = false
mediaType = "text/gemini"
protocol = "gemini://"
permalinkable = true
path = "gemini/"
noUgly = true

[outputFormats.GEMRSS]
name = "GEMRSS"
isHTML = false
mediaType = "application/rss+xml"
protocol = "gemini://"
path = "gemini/"

[outputs]
section = ["HTML", "RSS", "GEMRSS"]
