baseURL = "https://hedy.tilde.cafe"
languageCode = "en-us"
title = "Hedy's Home"
uglyurls = true

[params]
src = "https://sr.ht/~hedy/site"

[taxonomies]
tag = "tags"

[permalinks]
posts = "/posts/:slug"

[menu]
  [[menu.main]]
      identifier = "posts"
	  name = "posts"
	  title = "posts"
	  url = "/posts.html"
	  weight = 10
  [[menu.main]]
      identifier = "about"
	  name = "about"
	  title = "about"
	  url = "/about.html"
	  weight = 20
  [[menu.main]]
      identifier = "projects"
	  name = "projects"
	  title = "about"
	  url = "/projects.html"
	  weight = 30
  [[menu.main]]
      identifier = "rss"
	  name = "rss"
	  title = "rss"
	  url = "/posts/index.xml"
	  weight = "40"

[markup.goldmark.renderer]
# Allows HTML in Markdown
unsafe = true

[mediaTypes]
[mediaTypes."text/gemini"]
suffixes = ["gmi"]

[outputFormats]
[outputFormats.Gemini]
name = "GEMTEXT"
isPlainText = true
isHTML = false
mediaType = "text/gemini"
protocol = "gemini://"
permalinkable = true
path = "gemini/"
noUgly = false

[mediaTypes."application/atom+xml"]
  suffixes = ["xml"]

[outputFormats.GEMATOM]
name = "GEMATOM"
mediaType = "application/atom+xml"
protocol = "gemini://"
rel = "alternate"
isPlainText = false
path = "gemini/"
isHTML = false
noUgly = false
permalinkable = false

[outputs]
section = ["HTML", "RSS", "GEMATOM"]
