baseURL = "https://home.hedy.dev/"
title = "~hedy's home"
languageCode = "en-us"
timeZone = "UTC"
copyright = "© ~hedy, CC-BY-SA"

# Yes. Because I like the /folder -> /folder/ redirects
uglyurls = false

enableGitInfo = true
pygmentsUseClasses = true
pygmentsCodeFences = true
disableHugoGeneratorInject = true

[params]
canonicalBaseURL = "https://home.hedy.dev/"
description = "~hedy's home: hedy's canonical web presence including contact information and a blog."
copyright = "CC-BY-SA"
copyrightLink = "https://creativecommons.org/licenses/by-sa/4.0/"
copyrightYearStart = "2021"

src = "https://github.com/hedyhli/site"
srcURLPrefix = "https://git.sr.ht/~hedy/site/tree/master/item/"
logURLPrefix = "https://git.sr.ht/~hedy/site/log/master/item/"

shortTitle = "~hedy"
suffixTitle = " | ~hedy"  # appended after specific page titles

feedTitle = "~hedy"
feedPrefixTitle = "~hedy: "

geminiRoot = "gemini://gmi.hedy.dev"
htmlBaseDomain = "home.hedy.dev"
geminiBaseDomain = "gmi.hedy.dev"

# true: Use shortcode pfp-name as the home link text in nav bar
# false: Use shortTitle there instead
navHomeUsePFPName = true

[author]
name = "hedy"
email = "hedy.dev@protonmail.com"

[taxonomies]
tag = "tags"

[permalinks]
posts = "/posts/:slug"

[menu]
[[menu.main]]
identifier = "posts"
name = "Posts"
title = "posts"
url = "/posts/"
weight = 10
[[menu.main]]
identifier = "about"
name = "About"
title = "about"
url = "/about/"
weight = 20
[[menu.main]]
identifier = "misc"
name = "Misc"
title = "misc"
url = "/misc/"
weight = 40
[[menu.main]]
identifier = "rss"
name = "RSS"
title = "rss"
url = "/posts/index.xml"
weight = 100

[markup.goldmark.renderer]
# Allow HTML in Markdown
unsafe = true

[mediaTypes]
[mediaTypes."text/gemini"]
suffixes = ["gmi"]
[mediaTypes."application/atom+xml"]
suffixes = ["xml"]

[outputFormats]
[outputFormats.gemtext]
isPlainText = true
isHTML = false
mediaType = "text/gemini"
protocol = "gemini://"
permalinkable = true
path = "gemini/"
ugly = true

[outputFormats.GEMATOM]
mediaType = "application/atom+xml"
protocol = "gemini://"
rel = "alternate"
isPlainText = false
path = "gemini/"
isHTML = false
noUgly = false
permalinkable = false

# https://gist.github.com/lpar/7ded35d8f52fef7490a5be92e6cd6937
[outputFormats.ATOM]
mediaType = "application/atom"
baseName = "atom"
isPlainText = false

[outputs]
section = ["HTML", "RSS", "GEMATOM", "ATOM"]

[minify]
minifyOutput = true
disableXML = true
disableHTML = true
