baseURL = "https://hedy.tilde.cafe"
languageCode = "en-us"
title = "Hedy's Site"
uglyurls = true

[params]
src = "https://sr.ht/~hedy/site"

[permalinks]
posts = "/posts/:slug"

[markup.goldmark.renderer]
# Allows HTML in Markdown
unsafe = true

[mediaTypes]
[mediaTypes."text/gemini"]
suffixes = ["gmi"]

[outputFormats]
[outputFormats.Gemini]
name = "GEMTEXT"
isPlainText = true
isHTML = false
mediaType = "text/gemini"
protocol = "gemini://"
permalinkable = true
path = "gemini/"
noUgly = false

[mediaTypes."application/atom+xml"]
  suffixes = ["xml"]

[outputFormats.GEMATOM]
name = "GEMATOM"
mediaType = "application/atom+xml"
protocol = "gemini://"
rel = "alternate"
isPlainText = false
path = "gemini/"
isHTML = false
noUgly = false
permalinkable = false

[outputs]
section = ["HTML", "RSS", "GEMATOM"]
