baseURL = "https://hedy.tilde.cafe/"
languageCode = "en-us"
title = "~hedy's home"

# Yes. Because I like the /folder -> /folder/ redirects
uglyurls = false

enableGitInfo = true
pygmentsUseClasses = true
pygmentsCodeFences = true
disableHugoGeneratorInject = true

[params]
src = "https://sr.ht/~hedy/site"
logURLPrefix = "https://git.sr.ht/~hedy/site/log/master/item/"
copyright = "© 2021 CC-BY-SA"

geminiRoot = "gemini://hedy.tilde.cafe"

[author]
name = "hedy"
email = "hedy@tilde.cafe"

[taxonomies]
tag = "tags"

[permalinks]
posts = "/posts/:slug"

[menu]
  [[menu.main]]
      identifier = "posts"
	  name = "posts"
	  title = "posts"
	  url = "posts/"
	  weight = 10
  [[menu.main]]
      identifier = "about"
	  name = "about"
	  title = "about"
	  url = "about/"
	  weight = 20
#  [[menu.main]]
#      identifier = "projects"
#	  name = "projects"
#	  title = "projects"
#	  url = "projects/"
#	  weight = 30
  [[menu.main]]
      identifier = "rss"
	  name = "rss"
	  title = "rss"
	  url = "posts/index.xml"
	  weight = 30

[markup.goldmark.renderer]
# Allows HTML in Markdown
unsafe = true

[mediaTypes]
[mediaTypes."text/gemini"]
suffixes = ["gmi"]

[outputFormats]
[outputFormats.Gemini]
name = "GEMTEXT"
isPlainText = true
isHTML = false
mediaType = "text/gemini"
protocol = "gemini://"
permalinkable = true
path = "gemini/"
noUgly = false
uglyurls = true

[mediaTypes."application/atom+xml"]
  suffixes = ["xml"]

[outputFormats.GEMATOM]
name = "GEMATOM"
mediaType = "application/atom+xml"
protocol = "gemini://"
rel = "alternate"
isPlainText = false
path = "gemini/"
isHTML = false
noUgly = false
permalinkable = false

[outputs]
section = ["HTML", "RSS", "GEMATOM"]

[webmentions]
newDir = "public"
oldDir = "old"
webmentionsFile = "mentions.json"
excludeSources = [
"/tags/*",
"/",
]
excludeDestinations = [
"https://hedy.tilde.cafe"
]
